#!/bin/bash
#
# @package alpine
# @author  Yannoff <https://github.com/yannoff>
# @license MIT
#

generate_dockerfile(){
    local dockerfile version
    version=$1
    dockerfile=./${version}/Dockerfile
    cat > ${dockerfile} <<TEMPLATE
#
# This file is auto-generated by update.sh
#
# @package alpine
# @author  Yannoff <https://github.com/yannoff>
# @license MIT
#

FROM alpine:${version}

MAINTAINER Yannoff <https://github.com/yannoff>

COPY keep-alive /usr/local/bin/keep-alive

RUN \
    apk --update --no-cache add bash; \
    ln -s /usr/local/bin/keep-alive /

ENTRYPOINT ["/keep-alive"]
TEMPLATE

}

if [ $# -eq 0 ]
then
    printf "Usage: %s <version> [<version> [<version>]]\n" $0
    exit 1
fi

for v in "$@"
do
    printf "Generating dockerfile for version %s..." ${v}
    mkdir -p $v 2>/dev/null
    cp keep-alive $v/
    generate_dockerfile $v
    printf "\033[01;32mOK\033[00m\n"
    if [ "latest" = "$v" ]
    then
        printf "Copying latest version to root Dockerfile..."
        cp latest/Dockerfile . 2>/dev/null
        printf "\033[01;32mOK\033[00m\n"
    fi
done
