#!/bin/sh
set -e

# Allow Xdebug extension activation via the XDEBUG_ENABLED custom environment variable
xdebug_config_file=${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini
if [ ${XDEBUG_ENABLED:-0} -eq 0 ]
then
    echo ';Xdebug extension disabled' >${xdebug_config_file}
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

# TODO Find a better way to guess if the file is a mounted volume
# If command is "php-fpm", run it as root
if [ "$1" = "php-fpm" ]
then
    pool_config_tpl=/usr/local/etc/php-fpm.d/www.ini
    pool_config_file=/usr/local/etc/php-fpm.d/www.conf
    if [ -w "${pool_config_file}"  -a -O "${pool_config_file}" ]
    then
        envsubst >$pool_config_file <$pool_config_tpl '$USER' '$GROUP'
    fi

    exec "$@"
else
    # else allow executing ALL commands via a given user, if passed via env variables
    su-exec ${USER:-0}:${GROUP:-0} "$@"
fi
