http.host: 0.0.0.0

# X-Pack Machine Learning module is not supported by Alpine
xpack.ml.enabled: false

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1
